import { cn } from "@/lib/cn";
import { intrinsicSize } from "@/lib/imageManifest";
import type { ServiceImage } from "@/content/types";

/**
 * The one way this site renders a photograph.
 *
 * Its whole job is the part that is easy to forget: stating intrinsic
 * `width`/`height`. Without them an <img> has no aspect ratio until its bytes
 * arrive, the browser reserves no space, and everything below it jumps when it
 * lands — Cumulative Layout Shift. The numbers come from lib/imageManifest.ts,
 * which is generated by reading the files, so they cannot drift out of sync
 * with the assets the way hand-written ones do.
 *
 * Declaring width/height does NOT fix the rendered size: every call site here
 * lays the image out with CSS (`object-cover` inside a sized box), and a CSS
 * width/height always wins over the attributes. The attributes only supply the
 * ratio used to reserve space.
 *
 * `priority` is for above-the-fold imagery only — the Marine hero. It swaps
 * lazy loading for an eager fetch at high priority. Using it on more than the
 * one LCP element per page just makes everything compete.
 */
export function Pic({
  image,
  className,
  imgClassName,
  priority = false,
  sizes,
}: {
  image: ServiceImage;
  className?: string;
  imgClassName?: string;
  priority?: boolean;
  sizes?: string;
}) {
  const size = intrinsicSize(image.jpg) ?? intrinsicSize(image.webp);

  return (
    <picture className={className}>
      <source srcSet={image.webp} type="image/webp" />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={image.jpg}
        alt={image.alt}
        width={size?.[0]}
        height={size?.[1]}
        sizes={sizes}
        loading={priority ? "eager" : "lazy"}
        // Always async: decoding on the main thread is exactly the kind of
        // synchronous work that shows up as a dropped frame mid-scroll.
        decoding="async"
        fetchPriority={priority ? "high" : undefined}
        className={cn(imgClassName)}
      />
    </picture>
  );
}
